version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IrVzyXsnkDwpOnyfISyHqxLmrAzGWRBE
      POSTGRES_DB: railway
    ports:
      - "24642:24642"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    image: backend_app:latest
    platform: linux/amd64
    environment:
      PORT: 3000
      DB_URL:jdbc: postgresql://autorack.proxy.rlwy.net:24642/railway
      DB_HOST: autorack.proxy.rlwy.net
      DB_PORT: 24642
      DB_NAME: railway
      DB_USER: postgres
      DB_PASSWORD: IrVzyXsnkDwpOnyfISyHqxLmrAzGWRBE

      GEMINI_API_KEY: AIzaSyANTnFkC5SE2k8mXWxp5EMx2oOv4yyQu7I
      GEMINI_MODEL_VERSION: gemini-1.5-pro
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
