version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IrVzyXsnkDwpOnyfISyHqxLmrAzGWRBE
      POSTGRES_DB: railway
    ports:
      - "24642:24642"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    image: backend_app:latest
    platform: linux/amd64
    environment:
      PORT: ${PORT}  
      DB_URL: ${DB_URL}  
      DB_HOST: ${DB_HOST}  
      DB_PORT: ${DB_PORT}  
      DB_NAME: ${DB_NAME}  
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}  
      GEMINI_API_KEY: ${GEMINI_API_KEY}  
      GEMINI_MODEL_VERSION: ${GEMINI_MODEL_VERSION}  
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
