export const PREDEFINED_KEYWORDS = {
  ambiance: [
    'quiet',
    'loud',
    'cozy',
    'modern',
    'traditional',
    'romantic',
    'family-friendly',
    'hipster',
    'minimalist',
    'luxurious',
    'rustic',
    'artistic',
    'casual',
    'vibrant',
    'relaxed',
    'bright',
    'dimly lit',
    'chic',
    'energetic',
    'calm',
    'elegant',
    'nostalgic'
  ],
  dietary: [
    'vegan',
    'vegetarian',
    'gluten-free',
    'dairy-free',
    'keto',
    'paleo',
    'halal',
    'kosher',
    'nut-free',
    'low-carb',
    'organic',
    'farm-to-table',
    'sustainable'
  ],
  features: [
    'wifi',
    'outdoor seating',
    'pet-friendly',
    'reservations',
    'takeout',
    'delivery',
    'live music',
    'board games',
    'parking',
    'accessible',
    'workspace-friendly',
    'kid-friendly',
    'late-night'
  ],
  coffee: [
    'espresso',
    'latte',
    'cappuccino',
    'cold brew',
    'pour over',
    'french press',
    'decaf',
    'macchiato',
    'flat white',
    'americano',
    'mocha',
    'nitro brew',
    'cortado',
    'iced coffee',
    'affogato',
    'ristretto'
  ],
  drinks: [
    'tea',
    'herbal tea',
    'green tea',
    'chai',
    'matcha',
    'smoothie',
    'milkshake',
    'hot chocolate',
    'lemonade',
    'juice',
    'kombucha',
    'sparkling water',
    'mocktail',
    'cocktail',
    'craft beer',
    'wine',
    'cold tea',
    'flavored latte',
    'fruit tea',
    'bubble tea'
  ],
  vibes: [
    'study-friendly',
    'social',
    'intimate',
    'artsy',
    'luxury',
    'casual',
    'party',
    'tranquil',
    'bohemian',
    'industrial',
    'community-oriented',
    'romantic',
    'adventurous',
    'playful',
    'festive',
    'welcoming'
  ]
};

export type PredefinedKeywords = typeof PREDEFINED_KEYWORDS;
