name: Code Formatter and Linter

on:
  pull_request:
    branches:
      - production
      - development
  push:
    branches:
      - production
      - development

jobs:
  format-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [frontend, backend]

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd ${{ matrix.folder }}
          if [ -f "package.json" ]; then
            npm install
          fi

      # Run Prettier (Code Formatter)
      - name: Run Prettier
        run: |
          cd ${{ matrix.folder }}
          npx prettier --write "**/*.{js,jsx,json,css,md}"

      # Run ESLint (Linter)
      - name: Run ESLint
        run: |
          cd ${{ matrix.folder }}
          npx eslint "**/*.{js,jsx}" --max-warnings=0
