name: Docker Image CI

on:
  push:
    branches:
      - "production"
  pull_request:
    branches:
      - "production"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
       
      # Install Docker Compose v2 (if it's not available)
      - name: Install Docker Compose
        run: |
         curl -sSL https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
         chmod +x /usr/local/bin/docker-compose

      # Log in to Docker Hub (you can set these secrets in GitHub settings)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      # Print environment variables for debugging
      - name: Debug Environment Variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
          echo "GEMINI_MODEL_VERSION=${{ secrets.GEMINI_MODEL_VERSION }}"
          echo "PORT=${{ secrets.PORT }}"
          echo "DB_URL=${{ secrets.DB_URL }}"
          echo "DB_HOST=${{ secrets.DB_HOST }}"
          echo "DB_PORT=${{ secrets.DB_PORT }}"
          echo "DB_NAME=${{ secrets.DB_NAME }}"
          echo "DB_USER=${{ secrets.DB_USER }}"
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"

      # Build the Docker image using Docker Compose
      - name: Build the Docker image using Docker Compose
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL_VERSION: ${{ secrets.GEMINI_MODEL_VERSION }}
          PORT: ${{ secrets.PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose -f backend/docker-compose.yml build

      - name: Tag Docker image
        run: |
          docker tag backend_app:latest fsong009/cafexpress:latest

      # Push the image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push fsong009/cafexpress:latest
